version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: appname_development
      MYSQL_ROOT_PASSWORD: ${password}
      MYSQL_USER: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
